# Generated by Django 4.0 on 2021-12-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='persue_code',
            field=models.UUIDField(default='django.db.models.AutoField', editable=False),
        ),
    ]
